### ISSUE TITLE
where i can set rectOfInterest property of AVCaptureMetadataOutput

### ISSUE THREAD

**Issue by KevinMac123** [yannickl/QRCodeReaderViewController#10]
hey i have to scan qrcode in specific frame and that frame is the dashed line layer that you have added, now what can i do?

**Comment by yannickl** [comment]
Hey,

the `AVCaptureMetadataOutput` is not visible yet but I'll make it available from the `QRCodeReader` object to allow you to improve the configurability.

Thanks

**Comment by yannickl** [comment]
I just pushed a new version with the metadataOuput property visible so you can update its own properties. :)

**Comment by KevinMac123** [comment]
Thank you so much for this update @yannickl
