### ISSUE TITLE
How to support inverted QR Codes?

### ISSUE THREAD

**Issue by carlosmellado** [yannickl/QRCodeReaderViewController#13]
Hi, I have expecting issues with inverted qr codes on devices lower than iPhone 5.

If I have a code with colored background and white QR, it cannot read nothing, unless I read it with an iPhone 5,5s,6...

If I invert this code with photoshop, it's readed well by all the devices...

There would be some fix to read "colored background" codes from all devices?

Thank you.

**Comment by yannickl** [comment]
Hi,

Unfortunately the `QRCodeReaderViewController` is based on the `AVFoundation` framework so I can't improve the scan performance.

May be the contrast is too weak... Here are the apple recommendations: https://developer.apple.com/library/ios/technotes/tn2325/_index.html#//apple_ref/doc/uid/DTS40013824-CH1-HOW_CAN_I_IMPROVE_SCANNING_RESULTS_ON_VERY_SMALL_OR_VERY_DENSE_CODES_
