### ISSUE TITLE
Torch and switch camera button placement

### ISSUE THREAD

**Issue by jlhonora** [yannickl/QRCodeReaderViewController#14]
I'm having trouble using the torch buttons, specifically in an iPhone 5c (haven't tried other devices). The clickable area is marked in red:

![barcode_error](https://cloud.githubusercontent.com/assets/1577721/11010452/abbf6592-84bd-11e5-9c19-3e022bd4aeac.jpg)

Is there a way of "lowering" the icons' placement? I tried with every option of UIModalPresentationStyle, but no luck. My Objective-C is not very good, but I'll attempt to fix it in the meantime :)

Thanks for the lib, works great.

**Comment by jlhonora** [comment]
Related to https://github.com/yannickl/QRCodeReader.swift/issues/35

**Comment by yannickl** [comment]
Thank you for the repport!

**Comment by jlhonora** [comment]
Awesome, thanks a ton!
