### ISSUE TITLE
'Cancel' button does not appear in portrait mode on iPhone 6

### ISSUE THREAD

**Issue by eudavidf** [yannickl/QRCodeReaderViewController#15]
Trying on an iPhone 6, the Cancel button only appears in landscape. When rotate to portrait disappears.

**Comment by yannickl** [comment]
It works great for me. Have you some sample of code or more details please?

**Comment by eudavidf** [comment]
True, in the example works fine. I'll try to find what I'm doing wrong and if I found it, I'll write it down here.
Thanks anyway!
