### ISSUE TITLE
Return back

### ISSUE THREAD

**Issue by teinpro** [yannickl/QRCodeReaderViewController#23]
I can not figure out how to go back even if i did not scan a qrcode.
In your guide there is a button called cancel but in mine it not appears, How can i resolve it ??
Can you help me please ?? 
![img_0127](https://cloud.githubusercontent.com/assets/21286314/18031368/d1db7ad2-6cdd-11e6-858e-53af8f12ab1f.PNG)

**Comment by yannickl** [comment]
That's strange, it should normally appears. Have you correctly set the cancel button title?

**Comment by teinpro** [comment]
How can i do that?

**Comment by yannickl** [comment]
Using the reuired initializer like in the readme:

```objective-c
// Create the reader object
QRCodeReader *reader = [QRCodeReader readerWithMetadataObjectTypes:@[AVMetadataObjectTypeQRCode]];

// Instantiate the view controller
QRCodeReaderViewController *vc = [QRCodeReaderViewController readerWithCancelButtonTitle:@"Cancel"
                                                                              codeReader:_reader
                                                                     startScanningAtLoad:YES
                                                                  showSwitchCameraButton:YES
                                                                         showTorchButton:YES];
```

**Comment by teinpro** [comment]
I am using the swift version
There is a white that ?

Here the code : 

`lazy var readerVC = QRCodeReaderViewController(metadataObjectTypes: [AVMetadataObjectTypeQRCode])
readerVC.completionBlock = {
            (result: QRCodeReaderResult?) in
            print(result!.value)
        }
        // Presents the readerVC as modal form sheet
        readerVC.modalPresentationStyle = .OverCurrentContext
        
        presentViewController(readerVC, animated: true, completion: nil)`

**Comment by yannickl** [comment]
Just use the `initWithCancelButtonTitle:metadataObjectTypes` initialiser instead:

```swift
QRCodeReaderViewController(cancelTitle: "Cancel", metadataObjectTypes: [AVMetadataObjectTypeQRCode])
```

If you are working with swift you should use the [QRCodeReader.swift](https://github.com/yannickl/QRCodeReader.swift) version.

**Comment by teinpro** [comment]
I have change as you said but still nothing
Here the code 
`
import QRCodeReader
import AVFoundation

lazy var readerVC = QRCodeReaderViewController(cancelButtonTitle : "Cancel" ,metadataObjectTypes: [AVMetadataObjectTypeQRCode])
// delegate pattern
        readerVC.delegate = self
        // Presents the readerVC as modal form sheet
        readerVC.modalPresentationStyle = .FormSheet
        presentViewController(readerVC, animated: true, completion: nil)
 
func reader(reader: QRCodeReaderViewController, didScanResult result: QRCodeReaderResult) {
        self.dismissViewControllerAnimated(true, completion: nil)
        let qrcode_valore =
       print( result.value)
    }
    
func readerDidCancel(reader: QRCodeReaderViewController) {
        self.dismissViewControllerAnimated(true, completion: nil)
    }
`
![img_0127](https://cloud.githubusercontent.com/assets/21286314/18065732/8147606e-6e35-11e6-866c-e3cf57d04c9d.PNG)

**Comment by yannickl** [comment]
That's really strange. Does it happened with the sample project?

**Comment by teinpro** [comment]
Okay finally I resolved the issue. Thanks for your help.

I read the sample project and used the following builder : 
`private func createReader() -> QRCodeReaderViewController {
        let builder = QRCodeViewControllerBuilder { builder in
            builder.reader          = QRCodeReader(metadataObjectTypes: [AVMetadataObjectTypeQRCode])
            builder.showTorchButton = true
            builder.showCancelButton = true
        }
        
        return QRCodeReaderViewController(builder: builder)
    }
`
