### ISSUE TITLE
Not found reference "_OBJC_CLASS_$_QRCodeReaderViewController"

### ISSUE THREAD

**Issue by bhdang53** [yannickl/QRCodeReaderViewController#25]
![screen shot 2016-10-11 at 11 39 32 am](https://cloud.githubusercontent.com/assets/22761299/19259006/b7e3b468-8fa7-11e6-8747-26161b4031a1.png)

**Comment by bhdang53** [comment]
I found solution for above issue.
Because I added QRCodeReaderViewController libarary by drag and drop folder into my project, it make project can not recognize this lib.
Therefore I re-add lib by way: copy lib into folder contain project, and then drag and drop lib into project in xcode. 
If your project setting look as this, you were success!
![screen shot 2016-10-11 at 11 53 46 am](https://cloud.githubusercontent.com/assets/22761299/19260451/d2c06cc0-8fb3-11e6-9c45-f34fa64b052f.png)

**Comment by yannickl** [comment]
Thank you for the tips!
