### ISSUE TITLE
Custom Layout

### ISSUE THREAD

**Issue by f33chobits** [yannickl/QRCodeReaderViewController#3]
Hey there，can we custom the reader controller layout using this controller?

**Comment by yannickl** [comment]
Hi,

Sorry don't understand your need, can you explain it more explicitly?

If you want update the layout of the reader view controller you can update the `setupAutoLayoutConstraints` methods inside the `QRCodeReaderViewController.m` file but I don't know if it is your problem.

**Comment by f33chobits** [comment]
Oh, I mean using custom controller, for examle, put a button above the QRReaderView, and the center of the controller has a QRReaderView to scan QRCode, and at the bottom there is another button,.e.g.

**Comment by yannickl** [comment]
Hi, sorry for the late.

I just pushed a new version of the library with the ability to use another view controller.
To do so you have to use the `QRCodeReader` object which aims to initialise all the `AVFoundation` components for you and you just need to get the `previewLayer` variable to display the camera on your own view.

You can check the `QRCodeReaderViewController` class to see how to use the `QRCodeReader` properly. ;)

**Comment by f33chobits** [comment]
That's awesome,thanks!
