### ISSUE TITLE
Repeat Call

### ISSUE THREAD

**Issue by 54dujianchao** [yannickl/QRCodeReaderViewController#31]
somehow  Repeat Call
- (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputMetadataObjects:(NSArray *)metadataObjects fromConnection:(AVCaptureConnection *)connection

result in 

 _reader setCompletionWithBlock  Repeat Call

could you help Solve it

**Comment by yannickl** [comment]
Do you stop the reading the first time the code is scanned?
